export const kanjiReadings = {
  // "kata" is the kun'yomi stem of 語る.
  // N5
  '一': { onyomi: ['ichi'], kunyomi: ['hito', 'hitotsu'] },
  '二': { onyomi: ['ni'], kunyomi: ['futatsu'] },
  '三': { onyomi: ['san'], kunyomi: ['mittsu'] },
  '四': { onyomi: ['shi'], kunyomi: ['yon', 'yotsu'] },
  '五': { onyomi: ['go'], kunyomi: ['itsutsu'] },
  '六': { onyomi: ['roku'], kunyomi: ['muttsu'] },
  '七': { onyomi: ['shichi'], kunyomi: ['nana', 'nanatsu'] },
  '八': { onyomi: ['hachi'], kunyomi: ['ya', 'yattsu'] },
  '九': { onyomi: ['kyuu', 'ku'], kunyomi: ['kokonotsu'] },
  '十': { onyomi: ['juu'], kunyomi: ['too'] },
  '百': { onyomi: ['hyaku'], kunyomi: [] },
  '千': { onyomi: ['sen'], kunyomi: ['chi'] },
  '円': { onyomi: ['en'], kunyomi: [] },
  '多': { onyomi: ['ta'], kunyomi: ['ooi'] },
  '少': { onyomi: ['shou'], kunyomi: ['sukunai'] },
  '日': { onyomi: ['nichi', 'jitsu'], kunyomi: ['hi', 'ka'] },
  '月': { onyomi: ['getsu', 'gatsu'], kunyomi: ['tsuki', 'zuki'] },
  '年': { onyomi: ['nen'], kunyomi: ['toshi'] },
  '時': { onyomi: ['ji'], kunyomi: ['toki'] },
  '分': { onyomi: ['fun', 'pun', 'bun'], kunyomi: ['wakeru', 'wakaru'] },
  '半': { onyomi: ['han'], kunyomi: [] },
  '今': { onyomi: ['kon'], kunyomi: ['ima'] },
  '午': { onyomi: ['go'], kunyomi: [] },
  '前': { onyomi: ['zen'], kunyomi: ['mae'] },
  '後': { onyomi: ['go', 'kou'], kunyomi: ['ato'] },
  '毎': { onyomi: ['mai'], kunyomi: [] },
  '週': { onyomi: ['shuu'], kunyomi: [] },
  '曜': { onyomi: ['you'], kunyomi: [] },
  '上': { onyomi: ['jou', 'shou'], kunyomi: ['ue', 'kami', 'ageru', 'agaru', 'noboru'] },
  '下': { onyomi: ['ka', 'ge'], kunyomi: ['shita', 'shimo', 'sagaru', 'sageru', 'kudaru', 'kudasu', 'oriru', 'orosu'] },
  '左': { onyomi: ['sa'], kunyomi: ['hidari'] },
  '右': { onyomi: ['u', 'yuu'], kunyomi: ['migi'] },
  '東': { onyomi: ['tou'], kunyomi: ['higashi'] },
  '西': { onyomi: ['sai', 'sei'], kunyomi: ['nishi'] },
  '南': { onyomi: ['nan'], kunyomi: ['minami'] },
  '北': { onyomi: ['hoku'], kunyomi: ['kita'] },
  '外': { onyomi: ['gai', 'ge'], kunyomi: ['soto', 'hoka', 'hazusu'] },
  '中': { onyomi: ['chuu'], kunyomi: ['naka', 'uchi'] },
  '先': { onyomi: ['sen'], kunyomi: ['saki'] },
  '大': { onyomi: ['dai', 'tai'], kunyomi: ['oo', 'ookii'] },
  '小': { onyomi: ['shou'], kunyomi: ['chii', 'chiisai', 'ko', 'o'] },
  '高': { onyomi: ['kou'], kunyomi: ['taka', 'takai'] },
  '安': { onyomi: ['an'], kunyomi: ['yasui'] },
  '新': { onyomi: ['shin'], kunyomi: ['atara', 'atarashii', 'arata'] },
  '古': { onyomi: ['ko'], kunyomi: ['furu', 'furui'] },
  '長': { onyomi: ['chou'], kunyomi: ['naga', 'nagai'] },
  '山': { onyomi: ['san'], kunyomi: ['yama'] },
  '川': { onyomi: ['sen'], kunyomi: ['kawa'] },
  '水': { onyomi: ['sui'], kunyomi: ['mizu'] },
  '木': { onyomi: ['moku', 'boku'], kunyomi: ['ki', 'ko'] },
  '火': { onyomi: ['ka'], kunyomi: ['hi'] },
  '土': { onyomi: ['do'], kunyomi: ['tsuchi'] },
  '田': { onyomi: ['den'], kunyomi: ['ta'] },
  '天': { onyomi: ['ten'], kunyomi: [] },
  '気': { onyomi: ['ki'], kunyomi: [] },
  '雨': { onyomi: ['u'], kunyomi: ['ame', 'ama'] },
  '電': { onyomi: ['den'], kunyomi: [] },
  '白': { onyomi: ['haku', 'byaku'], kunyomi: ['shiro', 'shiroi'] },
  '黒': { onyomi: ['koku'], kunyomi: ['kuroi'] },
  '青': { onyomi: ['sei', 'shou'], kunyomi: ['ao', 'aoi'] },
  '人': { onyomi: ['jin', 'nin'], kunyomi: ['hito'] },
  '友': { onyomi: [], kunyomi: ['tomo'] },
  '男': { onyomi: ['dan', 'nan'], kunyomi: ['otoko'] },
  '女': { onyomi: ['jo', 'nyo'], kunyomi: ['onna', 'me'] },
  '子': { onyomi: ['shi', 'su'], kunyomi: ['ko'] },
  '父': { onyomi: ['fu'], kunyomi: ['chichi'] },
  '母': { onyomi: ['bo'], kunyomi: ['haha'] },
  '名': { onyomi: ['mei', 'myou'], kunyomi: ['na'] },
  '目': { onyomi: ['moku', 'boku'], kunyomi: ['me', 'ma'] },
  '耳': { onyomi: ['ji'], kunyomi: ['mimi'] },
  '手': { onyomi: ['shu'], kunyomi: ['te', 'ta'] },
  '足': { onyomi: ['soku'], kunyomi: ['ashi', 'ta'] },
  '口': { onyomi: ['kou', 'ku'], kunyomi: ['kuchi'] },
  '学': { onyomi: ['gaku'], kunyomi: ['manabu'] },
  '生': { onyomi: ['sei', 'shou'], kunyomi: ['i', 'umu', 'umareru', 'nama', 'haeru'] },
  '校': { onyomi: ['kou'], kunyomi: [] },
  '店': { onyomi: ['ten'], kunyomi: ['mise'] },
  '休': { onyomi: ['kyuu'], kunyomi: ['yasumu'] },
  '食': { onyomi: ['shoku', 'jiki'], kunyomi: ['taberu', 'kuu'] },
  '飲': { onyomi: ['in'], kunyomi: ['nomu'] },
  '見': { onyomi: ['ken'], kunyomi: ['mi', 'miru', 'mieru', 'miseru'] },
  '行': { onyomi: ['kou', 'gyou', 'an'], kunyomi: ['iku', 'yuku', 'okonau'] },
  '本': { onyomi: ['hon'], kunyomi: ['moto'] },
  '文': { onyomi: ['bun', 'mon'], kunyomi: [] },
  '字': { onyomi: ['ji'], kunyomi: ['aza'] },
  '語': { onyomi: ['go'], kunyomi: ['kata', 'kataru'] },
  '話': { onyomi: ['wa'], kunyomi: ['hanashi', 'hanasu'] },
  '読': { onyomi: ['doku', 'toku'], kunyomi: ['yomu'] },
  '書': { onyomi: ['sho'], kunyomi: ['kaku'] },
  '聞': { onyomi: ['bun', 'mon'], kunyomi: ['kiku', 'kikoeru'] },
  '言': { onyomi: ['gen', 'gon'], kunyomi: ['iu', 'koto'] },
  '買': { onyomi: ['bai'], kunyomi: ['kau'] },
  '来': { onyomi: ['rai'], kunyomi: ['kuru', 'ki'] },
  '帰': { onyomi: ['ki'], kunyomi: ['kaeru'] },
  '入': { onyomi: ['nyuu'], kunyomi: ['hairu', 'iru', 'ireru'] },
  '出': { onyomi: ['shutsu', 'sui'], kunyomi: ['deru', 'dasu'] },
  '会': { onyomi: ['kai', 'e'], kunyomi: ['au'] },
  '車': { onyomi: ['sha'], kunyomi: ['kuruma'] },
  '駅': { onyomi: ['eki'], kunyomi: [] },
  '国': { onyomi: ['koku'], kunyomi: ['kuni'] },
  // N4
  '事': { onyomi: ['ji'], kunyomi: ['koto'] },
  '使': { onyomi: ['shi'], kunyomi: ['tsukau'] },
  '待': { onyomi: ['tai'], kunyomi: ['matsu'] },
  '持': { onyomi: ['ji'], kunyomi: ['motsu'] },
  '始': { onyomi: ['shi'], kunyomi: ['hajimeru'] },
  '終': { onyomi: ['shuu'], kunyomi: ['owaru'] },
  '開': { onyomi: ['kai'], kunyomi: ['hiraku', 'hirakeru', 'aku', 'akeru'] },
  '閉': { onyomi: ['hei'], kunyomi: ['shimeru', 'shimaru', 'tojiru', 'tozasu'] },
  '動': { onyomi: ['dou'], kunyomi: ['ugoku', 'ugokasu'] },
  '働': { onyomi: ['dou'], kunyomi: ['hataraku'] },
  '教': { onyomi: ['kyou'], kunyomi: ['oshieru', 'oshie'] },
  '習': { onyomi: ['shuu'], kunyomi: ['narau'] },
  '考': { onyomi: ['kou'], kunyomi: ['kangaeru', 'kangae'] },
  '知': { onyomi: ['chi'], kunyomi: ['shiru'] },
  '思': { onyomi: ['shi'], kunyomi: ['omou', 'omoi'] },
  '忘': { onyomi: ['bou'], kunyomi: ['wasureru', 'wasure'] },
  '覚': { onyomi: ['kaku'], kunyomi: ['oboeru', 'sameru', 'samasu', 'satoru'] },
  '答': { onyomi: ['tou'], kunyomi: ['kotaeru', 'kotae'] },
  '問': { onyomi: ['mon'], kunyomi: ['tou', 'toi'] },
  '勉': { onyomi: ['ben'], kunyomi: [] },
  '作': { onyomi: ['saku'], kunyomi: ['tsukuru'] },
  '送': { onyomi: ['sou'], kunyomi: ['okuru'] },
  '返': { onyomi: ['hen'], kunyomi: ['kaesu', 'kaeru'] },
  '借': { onyomi: ['shaku'], kunyomi: ['kariru'] },
  '貸': { onyomi: ['tai'], kunyomi: ['kasu'] },
  '払': { onyomi: ['futsu'], kunyomi: ['harau'] },
  '選': { onyomi: ['sen'], kunyomi: ['erabu', 'yoru'] },
  '起': { onyomi: ['ki'], kunyomi: ['okiru', 'okosu'] },
  '寝': { onyomi: ['shin'], kunyomi: ['neru', 'nerasu'] },
  '泳': { onyomi: ['ei'], kunyomi: ['oyogu'] },
  '走': { onyomi: ['sou'], kunyomi: ['hashiru'] },
  '歩': { onyomi: ['ho'], kunyomi: ['aruku', 'ayumu'] },
  '渡': { onyomi: ['to'], kunyomi: ['wataru', 'watasu'] },
  '乗': { onyomi: ['jou'], kunyomi: ['noru', 'noseru'] },
  '降': { onyomi: ['kou'], kunyomi: ['oriru', 'orosu', 'furu'] },
  '止': { onyomi: ['shi'], kunyomi: ['tomaru', 'tomeru'] },
  '通': { onyomi: ['tsuu', 'tsu'], kunyomi: ['tooru', 'kayou'] },
  '進': { onyomi: ['shin'], kunyomi: ['susumu', 'susumeru'] },
  '取': { onyomi: ['shu'], kunyomi: ['toru'] },
  '直': { onyomi: ['choku', 'jiki'], kunyomi: ['naosu', 'naoru'] },
  '明': { onyomi: ['mei', 'myou'], kunyomi: ['aka', 'akarui', 'akeru', 'aku'] },
  '暗': { onyomi: ['an'], kunyomi: ['kurai'] },
  '強': { onyomi: ['kyou', 'gou'], kunyomi: ['tsuyo', 'tsuyoi', 'shii'] },
  '弱': { onyomi: ['jaku'], kunyomi: ['yowai'] },
  '早': { onyomi: ['sou'], kunyomi: ['hayai'] },
  '遅': { onyomi: ['chi'], kunyomi: ['oso', 'osoi', 'okureru'] },
  '重': { onyomi: ['juu', 'chou'], kunyomi: ['omo', 'omoi', 'kasaneru', 'kasanaru'] },
  '軽': { onyomi: ['kei'], kunyomi: ['karui'] },
  '広': { onyomi: ['kou'], kunyomi: ['hiro', 'hiroi', 'hirogaru', 'hirogeru'] },
  '低': { onyomi: ['tei'], kunyomi: ['hikui'] },
  '良': { onyomi: ['ryou'], kunyomi: ['yo', 'yoi'] },
  '悪': { onyomi: ['aku'], kunyomi: ['warui'] },
  '楽': { onyomi: ['raku', 'gaku'], kunyomi: ['tanoshii', 'tanoshimu'] },
  '正': { onyomi: ['sei', 'shou'], kunyomi: ['tada', 'tadashii', 'tadasu'] },
  '暖': { onyomi: ['dan'], kunyomi: ['atatakai'] },
  '寒': { onyomi: ['kan'], kunyomi: ['samui'] },
  '暑': { onyomi: ['sho'], kunyomi: ['atsui'] },
  '涼': { onyomi: ['ryou'], kunyomi: ['suzushii'] },
  '太': { onyomi: ['tai', 'ta'], kunyomi: ['futo', 'futoi', 'futoru'] },
  '細': { onyomi: ['sai'], kunyomi: ['hoso', 'hosoi', 'komakai'] },
  '丸': { onyomi: ['gan'], kunyomi: ['marui'] },
  '美': { onyomi: ['bi'], kunyomi: ['utsukushii'] },
  '若': { onyomi: ['jaku'], kunyomi: ['wakai'] },
  '忙': { onyomi: ['bou'], kunyomi: ['isogashii'] },
  '静': { onyomi: ['sei', 'jou'], kunyomi: ['shizuka', 'shizumaru', 'shizumeru'] },
  '元': { onyomi: ['gen', 'gan'], kunyomi: ['moto'] },
  '真': { onyomi: ['shin'], kunyomi: ['makoto'] },
  '同': { onyomi: ['dou'], kunyomi: ['onaji'] },
  '別': { onyomi: ['betsu'], kunyomi: [] },
  '特': { onyomi: ['toku'], kunyomi: [] },
  '必': { onyomi: ['hitsu'], kunyomi: [] },
  '変': { onyomi: ['hen'], kunyomi: ['kawaru', 'kaeru'] },
  '困': { onyomi: ['kon'], kunyomi: ['komaru'] },
  '疲': { onyomi: ['hi'], kunyomi: ['tsukareru'] },
  '痛': { onyomi: ['tsuu'], kunyomi: ['ita', 'itai'] },
  '幸': { onyomi: ['kou'], kunyomi: ['shiawase', 'saiwai'] },
  '悲': { onyomi: ['hi'], kunyomi: ['kanashii'] },
  '怖': { onyomi: ['fu'], kunyomi: ['kowai'] },
  '深': { onyomi: ['shin'], kunyomi: ['fuka', 'fukai', 'fukamaru', 'fukameru'] },
  '浅': { onyomi: ['sen'], kunyomi: ['asai'] },
  '旅': { onyomi: ['ryo'], kunyomi: ['tabi'] },
  '館': { onyomi: ['kan'], kunyomi: [] },
  '道': { onyomi: ['dou'], kunyomi: ['michi'] },
  '近': { onyomi: ['kin'], kunyomi: ['chikai'] },
  '遠': { onyomi: ['en'], kunyomi: ['tooi'] },
  '町': { onyomi: ['chou'], kunyomi: ['machi'] },
  '市': { onyomi: ['shi', 'ichi'], kunyomi: [] },
  '場': { onyomi: ['jou'], kunyomi: ['ba'] },
  '所': { onyomi: ['sho'], kunyomi: ['tokoro'] },
  '建': { onyomi: ['ken'], kunyomi: ['tateru'] },
  '病': { onyomi: ['byou'], kunyomi: ['yamai'] },
  '院': { onyomi: ['in'], kunyomi: [] },
  '区': { onyomi: ['ku'], kunyomi: [] },
  '都': { onyomi: ['to', 'tsu'], kunyomi: ['miyako'] },
  '県': { onyomi: ['ken'], kunyomi: [] },
  '村': { onyomi: ['son'], kunyomi: ['mura'] },
  '島': { onyomi: ['tou'], kunyomi: ['shima'] },
  '橋': { onyomi: ['kyou'], kunyomi: ['hashi'] },
  '池': { onyomi: ['chi'], kunyomi: ['ike'] },
  '寺': { onyomi: ['ji'], kunyomi: ['tera'] },
  '神': { onyomi: ['shin', 'jin'], kunyomi: ['kami'] },
  '門': { onyomi: ['mon'], kunyomi: ['kado'] },
  '階': { onyomi: ['kai'], kunyomi: [] },
  '室': { onyomi: ['shitsu'], kunyomi: ['muro'] },
  '屋': { onyomi: ['oku'], kunyomi: ['ya'] },
  '堂': { onyomi: ['dou'], kunyomi: [] },
  '港': { onyomi: ['kou'], kunyomi: ['minato'] },
  '船': { onyomi: ['sen'], kunyomi: ['fune'] },
  '部': { onyomi: ['bu'], kunyomi: [] },
  '工': { onyomi: ['kou', 'ku'], kunyomi: [] },
  '庭': { onyomi: ['tei'], kunyomi: ['niwa'] },
  '角': { onyomi: ['kaku'], kunyomi: ['kado', 'tsuno'] },
  '地': { onyomi: ['chi', 'ji'], kunyomi: [] },
  '図': { onyomi: ['zu', 'to'], kunyomi: [] },
  '坂': { onyomi: ['han'], kunyomi: ['saka'] },
  '岸': { onyomi: ['gan'], kunyomi: ['kishi'] },
  '湖': { onyomi: ['ko'], kunyomi: ['mizuumi'] },
  '森': { onyomi: ['shin'], kunyomi: ['mori'] },
  '原': { onyomi: ['gen'], kunyomi: ['hara'] },
  '岩': { onyomi: ['gan'], kunyomi: ['iwa'] },
  '家': { onyomi: ['ka', 'ke'], kunyomi: ['ie', 'uchi'] },
  '族': { onyomi: ['zoku'], kunyomi: [] },
  '親': { onyomi: ['shin'], kunyomi: ['oya', 'shitashii'] },
  '兄': { onyomi: ['kyou'], kunyomi: ['ani'] },
  '姉': { onyomi: ['shi'], kunyomi: ['ane'] },
  '弟': { onyomi: ['tei', 'dai'], kunyomi: ['otouto'] },
  '妹': { onyomi: ['mai'], kunyomi: ['imouto'] },
  '夫': { onyomi: ['fu', 'fuu'], kunyomi: ['otto'] },
  '妻': { onyomi: ['sai'], kunyomi: ['tsuma'] },
  '彼': { onyomi: ['hi'], kunyomi: ['kare'] },
  '員': { onyomi: ['in'], kunyomi: [] },
  '社': { onyomi: ['sha'], kunyomi: ['yashiro'] },
  '者': { onyomi: ['sha'], kunyomi: ['mono'] },
  '皆': { onyomi: ['kai'], kunyomi: ['mina', 'minna'] },
  '誰': { onyomi: [], kunyomi: ['dare'] },
  '君': { onyomi: ['kun'], kunyomi: ['kimi'] },
  '代': { onyomi: ['dai', 'tai'], kunyomi: ['yo', 'shiro'] },
  '世': { onyomi: ['sei', 'se'], kunyomi: ['yo'] },
  '界': { onyomi: ['kai'], kunyomi: [] },
  '主': { onyomi: ['shu', 'su'], kunyomi: ['nushi', 'omo'] },
  '他': { onyomi: ['ta'], kunyomi: ['hoka'] },
  '客': { onyomi: ['kyaku', 'kaku'], kunyomi: [] },
  '民': { onyomi: ['min'], kunyomi: ['tami'] },
  '政': { onyomi: ['sei'], kunyomi: [] },
  '役': { onyomi: ['yaku'], kunyomi: [] },
  '仕': { onyomi: ['shi', 'ji'], kunyomi: ['tsukaeru'] },
  '産': { onyomi: ['san'], kunyomi: ['umu', 'umareru'] },
  '像': { onyomi: ['zou'], kunyomi: [] },
  '身': { onyomi: ['shin'], kunyomi: ['mi'] },
  '心': { onyomi: ['shin'], kunyomi: ['kokoro'] },
  '力': { onyomi: ['ryoku', 'riki'], kunyomi: ['chikara'] },
  '声': { onyomi: ['sei', 'shou'], kunyomi: ['koe'] },
  '式': { onyomi: ['shiki'], kunyomi: [] },
  '結': { onyomi: ['ketsu'], kunyomi: ['musubu', 'yuu'] },
  '婚': { onyomi: ['kon'], kunyomi: [] },
  '留': { onyomi: ['ryuu', 'ru'], kunyomi: ['tomaru', 'tomeru'] },
  '訪': { onyomi: ['hou'], kunyomi: ['otozureru', 'tazuneru'] },
  '信': { onyomi: ['shin'], kunyomi: [] },
  '約': { onyomi: ['yaku'], kunyomi: [] },
  '交': { onyomi: ['kou'], kunyomi: ['majiwaru', 'majiru', 'mazeru'] },
  '薬': { onyomi: ['yaku'], kunyomi: ['kusuri'] },
  '鳥': { onyomi: ['chou'], kunyomi: ['tori'] },
  '魚': { onyomi: ['gyo'], kunyomi: ['uo', 'sakana'] },
  '肉': { onyomi: ['niku'], kunyomi: [] },
  '野': { onyomi: ['ya'], kunyomi: ['no'] },
  '菜': { onyomi: ['sai'], kunyomi: ['na'] },
  '茶': { onyomi: ['cha', 'sa'], kunyomi: [] },
  '米': { onyomi: ['bei'], kunyomi: ['kome'] },
  '春': { onyomi: ['shun'], kunyomi: ['haru'] },
  '夏': { onyomi: ['ka', 'ge'], kunyomi: ['natsu'] },
  '秋': { onyomi: ['shuu'], kunyomi: ['aki'] },
  '冬': { onyomi: ['tou'], kunyomi: ['fuyu'] },
  '朝': { onyomi: ['chou'], kunyomi: ['asa'] },
  '昼': { onyomi: ['chuu'], kunyomi: ['hiru'] },
  '夜': { onyomi: ['ya'], kunyomi: ['yoru'] },
  '夕': { onyomi: ['seki'], kunyomi: ['yuu'] },
  '晴': { onyomi: ['sei'], kunyomi: ['hareru'] },
  '曇': { onyomi: ['don'], kunyomi: ['kumoru'] },
  '雪': { onyomi: ['setsu'], kunyomi: ['yuki'] },
  '風': { onyomi: ['fuu', 'fu'], kunyomi: ['kaze'] },
  '雲': { onyomi: ['un'], kunyomi: ['kumo'] },
  '霧': { onyomi: ['mu'], kunyomi: ['kiri'] },
  '雷': { onyomi: ['rai'], kunyomi: ['kaminari'] },
  '氷': { onyomi: ['hyou'], kunyomi: ['koori'] },
  '波': { onyomi: ['ha'], kunyomi: ['nami'] },
  '草': { onyomi: ['sou'], kunyomi: ['kusa'] },
  '花': { onyomi: ['ka'], kunyomi: ['hana'] },
  '虫': { onyomi: ['chuu'], kunyomi: ['mushi'] },
  '星': { onyomi: ['sei', 'shou'], kunyomi: ['hoshi'] },
  '光': { onyomi: ['kou'], kunyomi: ['hikari'] },
  '谷': { onyomi: ['koku'], kunyomi: ['tani'] },
  '度': { onyomi: ['do', 'taku'], kunyomi: ['tabi'] },
  '末': { onyomi: ['matsu', 'batsu'], kunyomi: ['sue'] },
  '初': { onyomi: ['sho'], kunyomi: ['hatsu', 'hajime'] },
  '昔': { onyomi: ['seki', 'shaku'], kunyomi: ['mukashi'] },
  '晩': { onyomi: ['ban'], kunyomi: [] },
  '葉': { onyomi: ['you', 'shou'], kunyomi: ['ha'] },
  '枝': { onyomi: ['shi'], kunyomi: ['eda'] },
  '根': { onyomi: ['kon'], kunyomi: ['ne'] },
  '実': { onyomi: ['jitsu'], kunyomi: ['mi', 'minoru'] },
  // Additional characters used in the N5/N4 compound examples.
  '番': { onyomi: ['ban'], kunyomi: ['tsugai'] },
  '間': { onyomi: ['kan', 'ken'], kunyomi: ['aida', 'ma'] },
  '辺': { onyomi: ['hen'], kunyomi: ['ata', 'atari'] },
  '舎': { onyomi: ['sha', 'seki'], kunyomi: ['yado'] },
  '具': { onyomi: ['gu'], kunyomi: ['sonaeru', 'tsubusa'] },
  '空': { onyomi: ['kuu'], kunyomi: ['sora', 'kara', 'aku', 'akeru', 'suku'] },
  '達': { onyomi: ['tatsu', 'datsu'], kunyomi: ['tachi'] },
  '供': { onyomi: ['kyou', 'ku'], kunyomi: ['sonaeru', 'tomo'] },
  '玉': { onyomi: ['gyoku'], kunyomi: ['tama'] },
  '鼻': { onyomi: ['bi'], kunyomi: ['hana'] },
  '科': { onyomi: ['ka'], kunyomi: [] },
  '紙': { onyomi: ['shi'], kunyomi: ['kami'] },
  '音': { onyomi: ['on', 'in'], kunyomi: ['oto', 'ne'] },
  '物': { onyomi: ['butsu', 'motsu'], kunyomi: ['mono'] },
  '銀': { onyomi: ['gin'], kunyomi: [] },
  '化': { onyomi: ['ka', 'ke'], kunyomi: ['bakasu'] },
  '漢': { onyomi: ['kan'], kunyomi: [] },
  '方': { onyomi: ['hou'], kunyomi: ['kata'] },
  '合': { onyomi: ['gou'], kunyomi: ['au', 'awasu', 'awaseru'] },
  '了': { onyomi: ['ryou'], kunyomi: [] },
  '労': { onyomi: ['rou'], kunyomi: ['negirau'] },
  '練': { onyomi: ['ren'], kunyomi: ['neru'] },
  '回': { onyomi: ['kai', 'e'], kunyomi: ['mawaru', 'mawasu'] },
  '題': { onyomi: ['dai'], kunyomi: [] },
  '金': { onyomi: ['kin', 'kon'], kunyomi: ['kane', 'kana'] },
  '支': { onyomi: ['shi'], kunyomi: ['sasaeru'] },
  '床': { onyomi: ['shou'], kunyomi: ['toko', 'yuka'] },
  '坊': { onyomi: ['bou'], kunyomi: [] },
  '散': { onyomi: ['san'], kunyomi: ['chiru', 'chirasu', 'chirakasu'] },
  '引': { onyomi: ['in'], kunyomi: ['hiku', 'hikeru'] },
  '接': { onyomi: ['setsu'], kunyomi: ['tsugu'] },
  '記': { onyomi: ['ki'], kunyomi: ['shirusu'] },
  '点': { onyomi: ['ten'], kunyomi: ['tsuku', 'tsukeru'] },
  '刻': { onyomi: ['koku'], kunyomi: ['kizamu'] },
  '要': { onyomi: ['you'], kunyomi: ['kaname', 'iru'] },
  '温': { onyomi: ['on'], kunyomi: ['atatameru', 'atatamaru', 'nuku'] },
  '器': { onyomi: ['ki'], kunyomi: ['utsuwa'] },
  '房': { onyomi: ['bou'], kunyomi: ['fusa'] },
  '面': { onyomi: ['men', 'ben'], kunyomi: ['omo', 'omote', 'tsura'] },
  '難': { onyomi: ['nan'], kunyomi: ['katai', 'muzukashii'] },
  '頭': { onyomi: ['tou', 'zu', 'to'], kunyomi: ['atama', 'kashira'] },
  '福': { onyomi: ['fuku'], kunyomi: [] },
  '恐': { onyomi: ['kyou'], kunyomi: ['osoreru', 'osoroshii'] },
  '路': { onyomi: ['ro'], kunyomi: ['ji'] },
  '住': { onyomi: ['juu'], kunyomi: ['sumu', 'sumau'] },
  '京': { onyomi: ['kyou', 'kei', 'kin'], kunyomi: ['miyako'] },
  '庁': { onyomi: ['chou'], kunyomi: [] },
  '段': { onyomi: ['dan'], kunyomi: [] },
  '海': { onyomi: ['kai'], kunyomi: ['umi'] },
  '畔': { onyomi: ['han'], kunyomi: ['hotori'] },
  '林': { onyomi: ['rin'], kunyomi: ['hayashi'] },
  '婦': { onyomi: ['fu'], kunyomi: ['yome'] },
  '治': { onyomi: ['ji', 'chi'], kunyomi: ['osameru', 'naosu', 'naoru'] },
  '画': { onyomi: ['ga', 'kaku'], kunyomi: [] },
  '自': { onyomi: ['ji', 'shi'], kunyomi: ['mizukara'] },
  '配': { onyomi: ['hai'], kunyomi: ['kubaru'] },
  '能': { onyomi: ['nou'], kunyomi: [] },
  '束': { onyomi: ['soku'], kunyomi: ['taba', 'tabaneru'] },
  '局': { onyomi: ['kyoku'], kunyomi: [] },
  '牛': { onyomi: ['gyuu'], kunyomi: ['ushi'] },
  '台': { onyomi: ['dai', 'tai'], kunyomi: [] },
  '昆': { onyomi: ['kon'], kunyomi: [] },
  '豆': { onyomi: ['tou', 'zu'], kunyomi: ['mame'] },
  '際': { onyomi: ['sai'], kunyomi: ['kiwa'] },
};

export function validateKanjiReadings(kanjiEntries) {
  const sourceKanji = new Set(kanjiEntries.map(({ jp_character }) => jp_character));
  if (
    [...sourceKanji].some(character => !Object.prototype.hasOwnProperty.call(kanjiReadings, character))
  ) {
    throw new Error('Kanji reading coverage mismatch: every kanaCharacters.kanji entry must have readings.');
  }

  const compoundKanji = new Set(
    kanjiEntries.flatMap(({ usage }) => usage ? [...usage.word].filter(character => /[\u3400-\u9fff]/u.test(character)) : [])
  );
  const allKanji = new Set([...sourceKanji, ...compoundKanji]);

  for (const jp_character of allKanji) {
    if (!Object.prototype.hasOwnProperty.call(kanjiReadings, jp_character)) {
      throw new Error(`Kanji reading coverage mismatch: missing compound reading for ${jp_character}.`);
    }
    const { onyomi, kunyomi } = kanjiReadings[jp_character];
    if (
      !Array.isArray(onyomi) ||
      !Array.isArray(kunyomi) ||
      [...onyomi, ...kunyomi].some(reading => typeof reading !== 'string' || !reading.trim())
    ) {
      throw new Error(`Invalid onyomi or kunyomi data for ${jp_character}.`);
    }
  }
}
