export const kanjiUsageMeanings = {
  '一': ['number one / best', 'nomor satu / terbaik'],
  '二': ['two people', 'dua orang'],
  '三': ['three people', 'tiga orang'],
  '四': ['April', 'bulan April'],
  '五': ['5 yen', '5 yen'],
  '六': ['June / sixth month', 'bulan keenam (Juni)'],
  '七': ['July', 'bulan Juli'],
  '八': ['August', 'bulan Agustus'],
  '九': ['September', 'bulan September'],
  '十': ['October', 'bulan Oktober'],
  '百': ['100 yen', '100 yen'],
  '千': ['1,000 yen', '1.000 yen'],
  '円': ['100 yen', '100 yen'],
  '多': ['many / much', 'banyak'],
  '少': ['a little / a few', 'sedikit'],
  '日': ['Sunday', 'hari Minggu'],
  '月': ['Monday', 'hari Senin'],
  '年': ['this year', 'tahun ini'],
  '時': ['time / hours', 'waktu / jam'],
  '分': ['five minutes', 'lima menit'],
  '半': ['half', 'setengah'],
  '今': ['today', 'hari ini'],
  '午': ['morning / a.m.', 'pagi / sebelum tengah hari'],
  '前': ['before / in front', 'sebelum / depan'],
  '後': ['afternoon / p.m.', 'sore / setelah tengah hari'],
  '毎': ['every day', 'setiap hari'],
  '週': ['this week', 'minggu ini'],
  '曜': ['Wednesday', 'hari Rabu'],
  '上': ['skillful / good at', 'terampil / pandai'],
  '下': ['unskillful / poor at', 'tidak terampil / kurang pandai'],
  '左': ['left hand', 'tangan kiri'],
  '右': ['right hand', 'tangan kanan'],
  '東': ['east exit', 'pintu keluar timur'],
  '西': ['west exit', 'pintu keluar barat'],
  '南': ['south exit', 'pintu keluar selatan'],
  '北': ['north exit', 'pintu keluar utara'],
  '外': ['foreign country', 'negara asing'],
  '中': ['middle school', 'sekolah menengah pertama'],
  '先': ['teacher', 'guru'],
  '大': ['university', 'universitas'],
  '小': ['elementary school', 'sekolah dasar'],
  '高': ['high school', 'sekolah menengah atas'],
  '安': ['cheap', 'murah'],
  '新': ['newspaper', 'koran'],
  '古': ['used book / old book', 'buku bekas / buku lama'],
  '長': ['long', 'panjang'],
  '山': ['volcano', 'gunung berapi'],
  '川': ['riverbank', 'tepi sungai'],
  '水': ['Wednesday', 'hari Rabu'],
  '木': ['Thursday', 'hari Kamis'],
  '火': ['Tuesday', 'hari Selasa'],
  '土': ['Saturday', 'hari Sabtu'],
  '田': ['countryside', 'pedesaan'],
  '天': ['weather', 'cuaca'],
  '気': ['healthy / energetic', 'sehat / bersemangat'],
  '雨': ['rain gear', 'perlengkapan hujan'],
  '電': ['train', 'kereta'],
  '白': ['black and white', 'hitam putih'],
  '黒': ['black and white', 'hitam putih'],
  '青': ['blue sky', 'langit biru'],
  '人': ['Japanese person', 'orang Jepang'],
  '友': ['friend', 'teman'],
  '男': ['boy / young man', 'anak laki-laki / pemuda'],
  '女': ['girl / young woman', 'anak perempuan / pemudi'],
  '子': ['child', 'anak'],
  '父': ['father (polite)', 'ayah'],
  '母': ['mother (polite)', 'ibu'],
  '名': ['name', 'nama'],
  '目': ['eyeball', 'bola mata'],
  '耳': ['ear, nose and throat clinic', 'klinik telinga, hidung, dan tenggorokan'],
  '手': ['letter', 'surat'],
  '足': ['footsteps', 'langkah kaki'],
  '口': ['entrance', 'pintu masuk'],
  '学': ['student', 'siswa / mahasiswa'],
  '生': ['student', 'siswa / mahasiswa'],
  '校': ['school', 'sekolah'],
  '店': ['shop assistant', 'pegawai toko'],
  '休': ['day off / holiday', 'hari libur'],
  '食': ['meal', 'makanan'],
  '飲': ['drink / beverage', 'minuman'],
  '見': ['study visit / observation', 'kunjungan belajar / pengamatan'],
  '行': ['bank', 'bank'],
  '本': ['Japan', 'Jepang'],
  '文': ['culture', 'budaya'],
  '字': ['Chinese character', 'huruf kanji'],
  '語': ['Japanese language', 'bahasa Jepang'],
  '話': ['telephone conversation', 'percakapan telepon'],
  '読': ['reading books', 'membaca buku'],
  '書': ['bookstore', 'toko buku'],
  '聞': ['newspaper', 'koran'],
  '言': ['word / language', 'kata / bahasa'],
  '買': ['shopping', 'berbelanja'],
  '来': ['next week', 'minggu depan'],
  '帰': ['returning to one’s country', 'pulang ke negara asal'],
  '入': ['entrance', 'pintu masuk'],
  '出': ['exit', 'pintu keluar'],
  '会': ['company', 'perusahaan'],
  '車': ['train', 'kereta'],
  '駅': ['in front of the station', 'di depan stasiun'],
  '国': ['foreign country', 'negara asing'],
  '事': ['work / job', 'pekerjaan'],
  '使': ['how to use', 'cara menggunakan'],
  '待': ['waiting room', 'ruang tunggu'],
  '持': ['feeling', 'perasaan'],
  '始': ['start / beginning', 'permulaan'],
  '終': ['completion / finish', 'penyelesaian / selesai'],
  '開': ['opening a shop', 'pembukaan toko'],
  '閉': ['closing a shop', 'penutupan toko'],
  '動': ['animal', 'hewan'],
  '働': ['labor / work', 'tenaga kerja / pekerjaan'],
  '教': ['classroom', 'ruang kelas'],
  '習': ['practice', 'latihan'],
  '考': ['way of thinking', 'cara berpikir'],
  '知': ['acquaintance', 'kenalan'],
  '思': ['memory / recollection', 'kenangan'],
  '忘': ['lost item', 'barang yang tertinggal'],
  '覚': ['to memorize / learn', 'mengingat / menghafal'],
  '答': ['answer / response', 'jawaban / tanggapan'],
  '問': ['question / problem', 'pertanyaan / soal'],
  '勉': ['study', 'belajar'],
  '作': ['composition / essay', 'karangan'],
  '送': ['sending / transmission', 'pengiriman / transmisi'],
  '返': ['reply', 'balasan'],
  '借': ['debt', 'utang'],
  '貸': ['lending / checkout', 'peminjaman'],
  '払': ['payment', 'pembayaran'],
  '選': ['athlete / player', 'atlet / pemain'],
  '起': ['waking up', 'bangun tidur'],
  '寝': ['oversleeping', 'bangun kesiangan'],
  '泳': ['swimming', 'berenang'],
  '走': ['running / driving', 'berlari / berkendara'],
  '歩': ['stroll', 'jalan-jalan'],
  '渡': ['to cross', 'menyeberang'],
  '乗': ['boarding a vehicle', 'naik kendaraan'],
  '降': ['getting off a vehicle', 'turun dari kendaraan'],
  '止': ['cancellation', 'pembatalan'],
  '通': ['commuting to school', 'pergi ke sekolah'],
  '進': ['going on to higher education', 'melanjutkan pendidikan'],
  '取': ['transaction', 'transaksi'],
  '直': ['directly', 'secara langsung'],
  '明': ['tomorrow', 'besok'],
  '暗': ['memorization', 'hafalan'],
  '強': ['strong wind', 'angin kencang'],
  '弱': ['weak point', 'titik lemah'],
  '早': ['early morning', 'pagi-pagi'],
  '遅': ['being late / tardiness', 'terlambat / keterlambatan'],
  '重': ['important', 'penting'],
  '軽': ['light meal', 'makanan ringan'],
  '広': ['open space / plaza', 'lapangan / alun-alun'],
  '低': ['low temperature', 'suhu rendah'],
  '良': ['good', 'baik'],
  '悪': ['insult / bad language', 'hinaan / kata-kata kasar'],
  '楽': ['musical instrument', 'alat musik'],
  '正': ['New Year / first month', 'Tahun Baru / bulan pertama'],
  '暖': ['heating', 'pemanas'],
  '寒': ['chill / feeling cold', 'rasa dingin / menggigil'],
  '暑': ['hot (weather)', 'panas'],
  '涼': ['cool / refreshing', 'sejuk'],
  '太': ['thick / fat', 'tebal / gemuk'],
  '細': ['narrow path', 'jalan sempit'],
  '丸': ['all day long', 'seharian penuh'],
  '美': ['beautiful woman', 'perempuan cantik'],
  '若': ['young person', 'anak muda'],
  '忙': ['busy', 'sibuk'],
  '静': ['quiet', 'tenang'],
  '元': ['energy / health', 'energi / kesehatan'],
  '真': ['serious', 'serius'],
  '同': ['same time / simultaneously', 'waktu yang sama / bersamaan'],
  '別': ['another person / stranger', 'orang lain / orang asing'],
  '特': ['special', 'khusus'],
  '必': ['necessary', 'perlu'],
  '変': ['very difficult / terrible', 'sulit sekali / gawat'],
  '困': ['difficulty / hardship', 'kesulitan'],
  '疲': ['fatigue / exhaustion', 'kelelahan'],
  '痛': ['headache', 'sakit kepala'],
  '幸': ['happiness / good fortune', 'kebahagiaan / keberuntungan'],
  '悲': ['sad', 'sedih'],
  '怖': ['fear / terror', 'ketakutan'],
  '深': ['late at night', 'larut malam'],
  '浅': ['shallow', 'dangkal'],
  '旅': ['travel / trip', 'perjalanan'],
  '館': ['library', 'perpustakaan'],
  '道': ['road', 'jalan'],
  '近': ['neighborhood', 'lingkungan sekitar'],
  '遠': ['school outing / excursion', 'piknik sekolah / karyawisata'],
  '町': ['town center', 'pusat kota kecil'],
  '市': ['city hall', 'balai kota'],
  '場': ['place / location', 'tempat'],
  '所': ['address', 'alamat'],
  '建': ['building', 'bangunan'],
  '病': ['hospital', 'rumah sakit'],
  '院': ['hospital', 'rumah sakit'],
  '区': ['ward office', 'kantor distrik'],
  '都': ['Tokyo Metropolis', 'Metropolis Tokyo'],
  '県': ['prefectural office', 'kantor prefektur'],
  '村': ['villager', 'penduduk desa'],
  '島': ['island country', 'negara kepulauan'],
  '橋': ['pedestrian bridge', 'jembatan penyeberangan'],
  '池': ['pond water', 'air kolam'],
  '寺': ['Buddhist temple', 'kuil Buddha'],
  '神': ['Shinto shrine', 'kuil Shinto'],
  '門': ['main gate', 'gerbang utama'],
  '階': ['stairs', 'tangga'],
  '室': ['classroom', 'ruang kelas'],
  '屋': ['bookstore', 'toko buku'],
  '堂': ['dining hall / cafeteria', 'ruang makan / kantin'],
  '港': ['airport', 'bandara'],
  '船': ['ship crew / sailor', 'awak kapal'],
  '部': ['room', 'kamar'],
  '工': ['factory', 'pabrik'],
  '庭': ['gardening / yard work', 'pekerjaan kebun'],
  '角': ['angle', 'sudut'],
  '地': ['underground', 'bawah tanah'],
  '図': ['map', 'peta'],
  '坂': ['slope / hill road', 'jalan menanjak'],
  '岸': ['coast', 'pantai'],
  '湖': ['lakeside', 'tepi danau'],
  '森': ['forest', 'hutan'],
  '原': ['open field', 'padang terbuka'],
  '岩': ['rocky place / rocky shore', 'area berbatu'],
  '家': ['family', 'keluarga'],
  '族': ['family', 'keluarga'],
  '親': ['close friend', 'sahabat dekat'],
  '兄': ['siblings / brothers', 'saudara kandung'],
  '姉': ['sisters', 'saudara perempuan'],
  '弟': ['siblings / brothers', 'saudara kandung'],
  '妹': ['sisters', 'saudara perempuan'],
  '夫': ['married couple', 'pasangan suami istri'],
  '妻': ['married couple', 'pasangan suami istri'],
  '彼': ['girlfriend', 'pacar perempuan'],
  '員': ['company employee', 'karyawan perusahaan'],
  '社': ['company', 'perusahaan'],
  '者': ['young person', 'anak muda'],
  '皆': ['everyone (polite)', 'semuanya'],
  '誰': ['someone', 'seseorang'],
  '君': ['you (plural / familiar)', 'kalian'],
  '代': ['era / period', 'zaman / periode'],
  '世': ['world', 'dunia'],
  '界': ['world', 'dunia'],
  '主': ['husband / master', 'suami / tuan'],
  '他': ['another person', 'orang lain'],
  '客': ['guest room', 'kamar tamu'],
  '民': ['citizens', 'warga negara'],
  '政': ['politics', 'politik'],
  '役': ['public office', 'kantor pemerintahan'],
  '仕': ['work / job', 'pekerjaan'],
  '産': ['production', 'produksi'],
  '像': ['image / picture', 'gambar'],
  '身': ['oneself', 'diri sendiri'],
  '心': ['worry', 'kekhawatiran'],
  '力': ['ability', 'kemampuan'],
  '声': ['loud voice', 'suara keras'],
  '式': ['wedding ceremony', 'upacara pernikahan'],
  '結': ['marriage', 'pernikahan'],
  '婚': ['marriage', 'pernikahan'],
  '留': ['study abroad', 'belajar di luar negeri'],
  '訪': ['visit', 'kunjungan'],
  '信': ['self-confidence', 'kepercayaan diri'],
  '約': ['promise', 'janji'],
  '交': ['traffic / transportation', 'lalu lintas / transportasi'],
  '薬': ['pharmacy', 'apotek'],
  '鳥': ['small bird', 'burung kecil'],
  '魚': ['fish shop', 'toko ikan'],
  '肉': ['beef', 'daging sapi'],
  '野': ['vegetables', 'sayuran'],
  '菜': ['vegetables', 'sayuran'],
  '茶': ['tea', 'teh'],
  '米': ['cooked white rice', 'nasi putih'],
  '春': ['spring vacation', 'liburan musim semi'],
  '夏': ['summer vacation', 'liburan musim panas'],
  '秋': ['autumn equinox', 'ekuinoks musim gugur'],
  '冬': ['winter vacation', 'liburan musim dingin'],
  '朝': ['this morning', 'pagi ini'],
  '昼': ['lunch break', 'istirahat siang'],
  '夜': ['tonight', 'malam ini'],
  '夕': ['evening', 'sore hari'],
  '晴': ['clear weather', 'cuaca cerah'],
  '曇': ['cloudy weather', 'cuaca berawan'],
  '雪': ['heavy snow', 'salju lebat'],
  '風': ['typhoon', 'topan'],
  '雲': ['clouds / outlook', 'awan / prospek'],
  '霧': ['drizzle / misty rain', 'hujan gerimis berkabut'],
  '雷': ['thunderstorm', 'hujan badai'],
  '氷': ['ice water', 'air es'],
  '波': ['wind and waves', 'angin dan ombak'],
  '草': ['plants and flowers', 'rerumputan dan bunga'],
  '花': ['fireworks', 'kembang api'],
  '虫': ['insect', 'serangga'],
  '星': ['starry sky', 'langit berbintang'],
  '光': ['sunlight', 'cahaya matahari'],
  '谷': ['valley', 'lembah'],
  '度': ['temperature', 'suhu'],
  '末': ['weekend', 'akhir pekan'],
  '初': ['for the first time', 'untuk pertama kalinya'],
  '昔': ['old story / folktale', 'cerita zaman dahulu'],
  '晩': ['this evening', 'malam ini'],
  '葉': ['word / language', 'kata / bahasa'],
  '枝': ['edamame', 'edamame'],
  '根': ['basis / root', 'dasar / akar'],
  '実': ['in reality / actually', 'sebenarnya / kenyataannya'],
};
